on: 
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Conditional
        if: contains(github.event.pull_request.labels.*.name, 'benchmark')
        run: echo "triggered"

